### ISSUE TITLE
missing genmsg component in cmakelists.txt

### ISSUE THREAD

**Issue by tkruse** [ros/common_msgs#1]
most of the packages in common_msgs do not use genmsg in :
find_package(catkin REQUIRED COMPONENTS genmsg ...)

even though they use the macros from genmsg. This does not cause failures in a catki workspace with e.g. std_msgs (because we have a single global macro namespace), but causes failure when building common_msgs or packages thereof in an isolated workspace.

Plenty of similar bugs may exist in any number of catkin packages, unless all catkin packages get build in isolation, such errors will surface only randomly.

**Comment by dirk-thomas** [comment]
This has been fixed in e0136ed821a868a0d1207a7ac031c7a19cb9fbf3
