### ISSUE TITLE
catkin_install_python

### ISSUE THREAD

**Issue by AJdoodler** [ros/common_msgs#104]
I am receiving the following error after running `catkin_make` 
```
-- +++ processing catkin package: 'actionlib_msgs'
-- ==> add_subdirectory(common_msgs/actionlib_msgs)
-- actionlib_msgs: 3 messages, 0 services
CMake Error at common_msgs/actionlib_msgs/CMakeLists.txt:19 (catkin_install_python):
  Unknown CMake command "catkin_install_python".


-- Configuring incomplete, errors occurred!
See also "/home/pi/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```
I installed the package using the following command:
```
cd ~/catkin_ws/src/
git clone https://github.com/ros/common_msgs
cd ~/catkin_ws/
```
I am very new to ROS and have been trying to find this issue online to no avail.  Any help would be greatly appreciated.

**Background info:**
Python 2.7
Ros Groovy
Raspberry Pi running Raspian GNU/Linux 8.0 (Jessie)

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

Though please note, that groovy has been eol'd for almost 3 years. I'd highly recommend using a newer distribution. http://wiki.ros.org/Distributions
