### ISSUE TITLE
point_cloud2.py not installed

### ISSUE THREAD

**Issue by tfoote** [ros/common_msgs#11]
It was missed in the catkinization. http://answers.ros.org/question/64836/common_msgs-package-missing-sensor_msgspoint_cloud2py-in-groovyprecise/

**Comment by dirk-thomas** [comment]
These changes break sensor_msgs. Installing the Python package which does not have a `__init__.py` file makes it unable to import the sensor_msgs.msg module. Please fix, backport and re-release nito Hydro asap since shadow-fixed is currently broken because of that.

**Comment by tfoote** [comment]
released in 1.10.2 https://github.com/ros/rosdistro/pull/1780
