### ISSUE TITLE
posewithcovariance array?

### ISSUE THREAD

**Issue by protobits** [ros/common_msgs#110]
Would it be possible to add an array message definition for PoseWithCovariance? This would be useful to publish history of poses with covariance in a single message, which is not currently possible.

**Comment by tfoote** [comment]
Generally I'd rather not just add an Array datatype. There are a few left over that are kept around for backwards compatibility. A container with an array takes the same number of lines to define as using the array synatax and doesn't improve sematnic meaning. 

It sounds like you have a specific use case with semantic meaning. I'd recommend making a custom msg with exactly what you want and a sematically meaningful name as well as possibly some other relevant metadata that would be relevant to making the contents of the message self contained.
