### ISSUE TITLE
what is the correct format of JointTrajectoryPoint?

### ISSUE THREAD

**Issue by inksci** [ros/common_msgs#115]
I always get such error:
error: field points[] must be of type [trajectory_msgs/JointTrajectoryPoint]
I do not know the correct format of JointTrajectoryPoint, can anybody give me an example?

**Comment by tfoote** [comment]
Please ask questions on https://answers.ros.org following our support guidelines: http://wiki.ros.org/Support

We look to keep the issue trackers focused on development.
