### ISSUE TITLE
New tag for Melodic, please?

### ISSUE THREAD

**Issue by mikepurvis** [ros/common_msgs#119]
Looks like the most recent one (1.12.5) was in 2016, and there have been a number of fixes that have gone in since. It'd be great to have a tag for that stuff:

http://repositories.ros.org/status_page/ros_melodic_default.html?q=common_msgs

**Comment by mikepurvis** [comment]
Ping

**Comment by tfoote** [comment]
1.12.6 created https://github.com/ros/common_msgs/releases/tag/1.12.6 and pushed to melodic https://github.com/ros/rosdistro/pull/17737  I'll make Indigo and Kinetic releases too but hold them for a coordinated rebuild.
