### ISSUE TITLE
actionlib_msgs are being installed into the wrong location

### ISSUE THREAD

**Issue by tspicer01** [ros/common_msgs#120]
Hello,

Starting with commit https://github.com/ros/common_msgs/commit/5276dce7ac2b118002d6e1fc0c305eb66d643d1c all of our actionlib_msgs are now being installed into the wrong location.

The are now being installed into  <install_space>/<devel_space>

Example:
Install space : /tmp/buildd/workspace/install
Devel space: /tmp/buildd/workspace/build/devel

Package: strategy_management_msgs

Actionlib msgs are now in : /tmp/buildd/workspace/install/share/strategy_management_msgs/tmp/buildd/workspace/build/devel/strategy_management_msgs/share/strategy_management_msgs/msg

All other messages are in their expected directory location under the install space.

Any help with this issue would be appreciated.

**Comment by mikepurvis** [comment]
Looks like this merged in #96. @mrjogo, can you comment on the issue?
