### ISSUE TITLE
What branch should I use for ROS kinetic?

### ISSUE THREAD

**Issue by walterinho** [ros/common_msgs#132]
Hi, I have a Raspberry Pi 3b+ with Raspbian stretch and I'm getting the error:

ERROR: No definition of [geometry] for OS [debian]

**Comment by tfoote** [comment]
Please ask questions on answers.ros.org following our support guidelines https://wiki.ros.org/Support This does not appear to be at all related to this repository. 

When you ask please make sure to include enough information to reproduce your problem.
