### ISSUE TITLE
Can not found CameraInfo under sensor_msgs namespace

### ISSUE THREAD

**Issue by lucasjinreal** [ros/common_msgs#145]
Hi, I just installed ros, but can not found sensor_msgs::CameraInfo on kinetic Ubuntu 16.04.

error:

```
 error: ‘CameraInfo’ in namespace ‘sensor_msgs’ does not name a type
   void cbCameraInfo(const sensor_msgs::CameraInfo msg_info);
                                        ^
In file included from /opt/ros/kinetic/include/ros/serialization.h:37:0,
                 from /opt/ros/kinetic/include/ros/publisher.h:34,
                 from /opt/ros/kinetic/include/ros/node_handle.h:32,
                 from /opt/ros/kinetic/include/ros/ros.h:45,

```

How could I include that anyway?

**Comment by tfoote** [comment]
That sounds like you're missing an include. 

Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
