### ISSUE TITLE
New Releases

### ISSUE THREAD

**Issue by DLu** [ros/common_msgs#167]
Requesting a new release of at least `noetic` that includes #164

**Comment by DLu** [comment]
Ping @hidmic ?

**Comment by hidmic** [comment]
Thanks for the bump @DLu. Yes we can make both Noetic and Melodic releases.

**Comment by hidmic** [comment]
https://github.com/ros/rosdistro/pull/27955 is up.

**Comment by DLu** [comment]
![thanks](https://media.giphy.com/media/WAfGpVI1pI3e/giphy.gif)

**Comment by hidmic** [comment]
https://github.com/ros/rosdistro/pull/27963 is up too.
