### ISSUE TITLE
'atoi' was not declared in this scope

### ISSUE THREAD

**Issue by Thomio-Watanabe** [ros/common_msgs#97]
I got this error from the following header:

    common_msgs/sensor_msgs/include/sensor_msgs/image_encodings.h

To solve it I had to add `#include<cstdlib>`

**Comment by tfoote** [comment]
Thanks, what is your development platform?

**Comment by Thomio-Watanabe** [comment]
ubuntu 14.04 - ROS Jade

**Comment by miquelmassot** [comment]
I still have this error in Kinetic 16.04 from debs. Is it possible to get a new release?

**Comment by marioney** [comment]
Same here, I have the same error message in Kinetic and ubuntu 16.04
